export type ShipFactionName = 'Klingon' | 'Romulan' | 'Pirate' | 'Independent' | 'Federation';

export const shipNames: Record<ShipFactionName, string[]> = {
  Klingon: [
    "I.K.S. Gr'oth",
    "I.K.S. Vor'nak",
    "I.K.S. Rotarran",
    "I.K.S. Negh'Var",
    "I.K.S. Bortas",
    "I.K.S. T'Acog",
    "I.K.S. Maht-H'a",
    "I.K.S. Hegh'ta",
    "I.K.S. Kang",
    "I.K.S. Kor",
    "I.K.S. Koloth",
    "I.K.S. Vorn",
    "Blade of Kahless",
    "Fist of Gowron",
    "Heart of Targ",
    "Bloodied D'k tahg",
    "Doom of Qu'Vat",
    "Martok's Pride",
  ],
  Romulan: [
    "I.R.W. Khazara",
    "I.R.W. T'Varo",
    "I.R.W. Haakona",
    "I.R.W. Praetus",
    "I.R.W. Decius",
    "I.R.W. S'Talon",
    "Serpent's Kiss",
    "Shadow's Wing",
    "Raptor's Claw",
    "Void Talon",
    "Nightwing",
    "Unseen Blade",
    "Deceiver's Smile",
    "T'Liss's Ghost",
    "The Devidien",
  ],
  Pirate: [
    "The Crimson Reaver",
    "Orion's Fury",
    "The Void Drifter",
    "The Black Star",
    "The Jackal's Tooth",
    "The Stolen Valor",
    "The Rogue Comet",
    "The 'Lucky' Break",
    "The Gutless Wonder",
    "The Scrap Heap",
    "The Debt Collector",
    "The Hazard Pay",
    "The Free Enterprise",
    "The Asteroid's Shadow",
  ],
  Independent: [
    "Stardust",
    "The Far Horizon",
    "The Lucky Charm",
    "The Wanderer",
    "The Venture",
    "The Prospector",
    "The Last Resort",
    "The Free Spirit",
    "The 'Honest' Trader",
    "The Ganymede Run",
    "The Solar Wind",
    "The Celestial Path",
  ],
  Federation: [
    "U.S.S. Stargazer",
    "U.S.S. Farragut",
    "U.S.S. Hood",
    "U.S.S. Lexington",
    "U.S.S. Potemkin",
    "U.S.S. Tsiolkovsky",
    "U.S.S. Righteous",
    "U.S.S. Valiant",
    "U.S.S. Intrepid",
    "U.S.S. Reliant",
    "U.S.S. Grissom",
    "U.S.S. Drake",
  ],
};
