export type ShipFactionName = 'Klingon' | 'Romulan' | 'Pirate' | 'Independent' | 'Federation';

export const shipNames: Record<ShipFactionName, string[]> = {
  Klingon: [
    "I.K.S. Gr'oth",
    "I.K.S. Vor'nak",
    "I.K.S. Rotarran",
    "I.K.S. Negh'Var",
    "I.K.S. Bortas",
    "I.K.S. T'Acog",
    "I.K.S. Maht-H'a",
    "I.K.S. Hegh'ta",
    "I.K.S. Kang",
    "I.K.S. Kor",
    "I.K.S. Koloth",
    "I.K.S. Vorn",
    "Blade of Kahless",
    "Fist of Gowron",
    "Heart of Targ",
    "Bloodied D'k tahg",
    "Doom of Qu'Vat",
    "Martok's Pride",
    "I.K.S. Ch'Tang",
    "I.K.S. Vor'cha",
    "I.K.S. K't'inga",
    "I.K.S. Somraw",
    "I.K.S. Durgath",
    "I.K.S. Pagh",
    "I.K.S. M'Char",
    "I.K.S. K'Vort",
    "I.K.S. T'Kuvma",
    "I.K.S. Duras",
    "Kahless's Wrath",
    "Gorkon's Hope",
    "Spear of Destiny",
    "The Unrelenting",
    "The Qatlh",
    "The Executioner's Blade",
    "The Sto-vo-kor's Herald",
  ],
  Romulan: [
    "I.R.W. Khazara",
    "I.R.W. T'Varo",
    "I.R.W. Haakona",
    "I.R.W. Praetus",
    "I.R.W. Decius",
    "I.R.W. S'Talon",
    "Serpent's Kiss",
    "Shadow's Wing",
    "Raptor's Claw",
    "Void Talon",
    "Nightwing",
    "Unseen Blade",
    "Deceiver's Smile",
    "T'Liss's Ghost",
    "The Devidien",
    "I.R.W. Valdore",
    "I.R.W. Terix",
    "I.R.W. Belak",
    "I.R.W. Mogai",
    "I.R.W. Norexan",
    "I.R.W. Pi",
    "Blade of the Tal Shiar",
    "Sela's Vengeance",
    "The Silent Talon",
    "The Whispering Death",
    "The Decloaked Dagger",
    "The Chulan's Fist",
    "The Veridian's Shadow",
    "The Unseen Hunter",
    "The Serpent's Coil",
  ],
  Pirate: [
    "The Crimson Reaver",
    "Orion's Fury",
    "The Void Drifter",
    "The Black Star",
    "The Jackal's Tooth",
    "The Stolen Valor",
    "The Rogue Comet",
    "The 'Lucky' Break",
    "The Gutless Wonder",
    "The Scrap Heap",
    "The Debt Collector",
    "The Hazard Pay",
    "The Free Enterprise",
    "The Asteroid's Shadow",
    "The Void Vulture",
    "The Star Scourge",
    "The Rustbucket",
    "The Last Gamble",
    "The Double-Cross",
    "The Ferengi's Folly",
    "The Nebulan Terror",
    "The Ion Shark",
    "The Black Market",
    "The Quick Escape",
    "The Unregistered",
    "The Shadow Runner",
    "The Broken Promise",
    "The Salvage King",
    "The Nova's Remnant",
  ],
  Independent: [
    "Stardust",
    "The Far Horizon",
    "The Lucky Charm",
    "The Wanderer",
    "The Venture",
    "The Prospector",
    "The Last Resort",
    "The Free Spirit",
    "The 'Honest' Trader",
    "The Ganymede Run",
    "The Solar Wind",
    "The Celestial Path",
    "The Stardust Wayfarer",
    "The Galactic Tramp",
    "The Cargo Cult",
    "The Lone Pilgrim",
    "The Far Trader",
    "The Unbound",
    "The Celestial Drifter",
    "The Nomad's Star",
    "The Open Sky",
    "The Eridani Voyager",
    "The Interstellar Courier",
    "The Quasar Runner",
    "The Frontier Spirit",
    "The Independent Star",
    "The Long Haul",
  ],
  Federation: [
    "U.S.S. Stargazer",
    "U.S.S. Farragut",
    "U.S.S. Hood",
    "U.S.S. Lexington",
    "U.S.S. Potemkin",
    "U.S.S. Tsiolkovsky",
    "U.S.S. Righteous",
    "U.S.S. Valiant",
    "U.S.S. Intrepid",
    "U.S.S. Reliant",
    "U.S.S. Grissom",
    "U.S.S. Drake",
    "U.S.S. Excelsior",
    "U.S.S. Odyssey",
    "U.S.S. Defiant",
    "U.S.S. Prometheus",
    "U.S.S. Voyager",
    "U.S.S. Galaxy",
    "U.S.S. Nebula",
    "U.S.S. Ambassador",
    "U.S.S. Sovereign",
    "U.S.S. Akira",
    "U.S.S. Pasteur",
    "U.S.S. Melbourne",
    "U.S.S. Yamato",
    "U.S.S. Kyushu",
    "U.S.S. Bradbury",
    "U.S.S. Constantinople",
  ],
};
